import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";

import ThemeApplier from "@/components/ThemeApplier";
import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap" // Add this to prevent font FOUC
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap" // Add this to prevent font FOUC
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeApplier />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
